name: CI - Test & Build on PR and Merge

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build
